export const menuCategories = [
  {
    id: 'desayunos',
    name: 'Desayunos',
    emoji: '☀️',
    items: [
      { name: 'Clásico', desc: 'Infusión + 2 medialunas + jugo exprimido', price: null },
      { name: 'Completo', desc: 'Infusión + 1 medialuna + 2 criollos + mermelada/queso + jugo exprimido + ensaladita de fruta', price: null },
      { name: 'Light', desc: 'Infusión + 3 tostadas integrales + mermelada/queso + jugo exprimido + ensaladita de fruta', price: null },
      { name: 'De la Casa', desc: 'Infusión + 3 tostadas integrales o de campo + 3 fetas jamón/queso + huevo revuelto + queso crema/manteca + jugo exprimido', price: null },
      { name: 'Omelette', desc: 'Infusión + omelette jamón y queso + jugo exprimido', price: null },
      { name: 'Francés', desc: 'Infusión + waffle (salado o dulce) + jugo exprimido', price: null },
      { name: 'Licuado', desc: 'Licuado o jugo exprimido + tostado', price: null },
      { name: 'Dulce Despertar', desc: 'Infusión/capuccino/submarino + porción de torta o 150gr de especialidad', price: null },
      { name: 'Energético', desc: 'Infusión + 2 tostadas con palta y huevo (pan de campo o integral) + jugo exprimido + yogurcito con granola', price: null },
    ],
  },
  {
    id: 'combos',
    name: 'Combos Desayuno y Merienda',
    emoji: '⭐',
    items: [
      { name: 'Combo Clásico', desc: 'Infusión + 2 medialunas', price: '$7.700', best: true },
      { name: 'Combo Clásico 2', desc: 'Infusión + 3 criollos', price: '$6.000', best: true },
      { name: 'Combo Torta', desc: 'Infusión + porción de torta a elección', price: '$10.500', best: true },
      { name: 'Combo Tostado', desc: 'Infusión o licuados + tostado', price: '$11.500' },
    ],
  },
  {
    id: 'combos-simples',
    name: 'Combos Simples',
    emoji: '☕',
    items: [
      { name: 'Taza doble + 3 criollos', desc: null, price: null },
      { name: 'Jarro + 2 criollos', desc: null, price: null },
      { name: 'Jarro + medialuna', desc: null, price: null },
      { name: 'Jarro + 2 criollos + mermelada/queso + jugo exprimido', desc: null, price: null },
    ],
  },
  {
    id: 'cafeteria',
    name: 'Infusiones / Cafetería',
    emoji: '☕',
    items: [
      { name: 'Café doble + syrup de pistacho', desc: null, price: null },
      { name: 'Jarro', desc: null, price: null },
      { name: 'Pocillo', desc: null, price: null },
      { name: 'Té', desc: null, price: null },
      { name: 'Capuchino', desc: null, price: null },
      { name: 'Submarino', desc: null, price: null },
      { name: 'Mocca', desc: null, price: null },
      { name: 'Pistacho', desc: null, price: null },
      { name: 'Café para llevar', desc: 'Infusión a elección', price: '$5.000', best: true },
    ],
  },
  {
    id: 'bebidas',
    name: 'Bebidas',
    emoji: '🥤',
    items: [
      { name: 'Licuado', desc: 'Frutilla, durazno o banana', price: '$6.500' },
      { name: 'Jugo exprimido de naranja', desc: null, price: '$6.500' },
      { name: 'Limonada y menta', desc: null, price: null },
      { name: 'Ensalada de fruta', desc: 'Manzana, pera, banana, kiwi y frutilla', price: '$5.500' },
      { name: 'Coca Cola 2.25L', desc: null, price: '$6.000' },
      { name: 'Coca Cola 1.5L', desc: null, price: '$4.500' },
      { name: 'Coca Cola / Zero / Sprite / Fanta 500ml', desc: null, price: '$3.000' },
      { name: 'Agua sin gas Bonaqua 500ml', desc: null, price: '$3.000' },
      { name: 'Cerveza 710ml', desc: null, price: null },
    ],
  },
  {
    id: 'salado',
    name: 'Date el Gusto (Salado)',
    emoji: '🥖',
    items: [
      { name: 'Baguette / Pan', desc: 'Jamón cocido + queso + lechuga y tomate + mayonesa', price: null },
      { name: 'Baguette Salame', desc: 'Salame + queso + lechuga y tomate + mayonesa', price: null },
      { name: 'Wafle salado (Jamón)', desc: 'Jamón + queso + queso crema + lechuga y tomate', price: null },
      { name: 'Wafle salado (Salame)', desc: 'Salame + queso + queso crema + lechuga y tomate', price: null },
      { name: 'Tostado Napolitano', desc: 'Pan árabe + jamón + queso + mayonesa, gratinado con mozzarella, tomate y orégano', price: null },
      { name: 'Tostado', desc: null, price: null },
      { name: 'Tostón palta y huevo', desc: '2 unidades', price: null },
      { name: 'Mafalda', desc: null, price: null },
      { name: 'Porción fiambre', desc: '3 fetas', price: null },
      { name: 'Huevo revuelto', desc: null, price: null },
      { name: 'Chipá', desc: '100gr', price: null },
    ],
  },
  {
    id: 'sandwiches',
    name: 'Sándwiches',
    emoji: '🥪',
    items: [
      { name: 'Sándwich de miga', desc: 'Jamón y queso', price: '$3.700', best: true },
      { name: 'Pebete', desc: 'Salame o jamón', price: '$3.700' },
    ],
  },
  {
    id: 'dulce',
    name: 'Dulce',
    emoji: '🍰',
    items: [
      { name: 'Wafle dulce', desc: 'Frutas + dulce de leche + miel', price: null },
      { name: 'Croissant', desc: null, price: null },
      { name: 'Porción de torta', desc: null, price: null },
      { name: 'Yogurt granola y fruta', desc: null, price: null },
      { name: 'Ensalada de frutas', desc: null, price: null },
      { name: 'Especialidad', desc: '100gr', price: null },
      { name: 'Factura', desc: null, price: null },
      { name: 'Dona', desc: null, price: null },
      { name: 'Pastelito', desc: null, price: null },
      { name: 'Alfajor maicena chocolate', desc: null, price: null },
    ],
  },
  {
    id: 'tortas',
    name: 'Tortas',
    emoji: '🎂',
    items: [
      { name: 'Torta Moka', desc: 'Porción', price: '$5.000' },
      { name: 'Torta Frutilla', desc: 'Porción', price: '$5.000' },
      { name: 'Torta Durazno', desc: 'Porción', price: '$5.000' },
      { name: 'Selva Negra', desc: 'Porción', price: '$5.000' },
    ],
  },
  {
    id: 'panaderia',
    name: 'Panadería',
    emoji: '🥐',
    items: [
      { name: '¼ Criollos hojaldre', desc: null, price: '$2.800', best: true },
      { name: '¼ Criollos comunes', desc: null, price: '$2.800', best: true },
      { name: '½ Docena facturas', desc: null, price: '$6.500', best: true },
      { name: '½ Docena medialunas', desc: null, price: '$6.500', best: true },
      { name: 'Pan 1kg', desc: null, price: '$4.000', best: true },
      { name: 'Prepizza rectangular', desc: null, price: '$4.000' },
      { name: 'Prepizza redonda', desc: null, price: '$3.100' },
      { name: 'Pan integral con semillas', desc: null, price: '$5.900' },
      { name: 'Pan de campo', desc: null, price: '$4.000' },
      { name: '¼ Pan salvado', desc: null, price: '$2.000' },
      { name: 'Bizcochos de grasa (100gr)', desc: null, price: '$1.900' },
      { name: 'Chalitas comunes (100gr)', desc: null, price: '$1.900' },
      { name: 'Chalitas con semillas (100gr)', desc: null, price: '$1.900' },
      { name: 'Tostadas (100gr)', desc: null, price: '$1.900' },
    ],
  },
  {
    id: 'masas-secas',
    name: 'Masas Secas',
    emoji: '🍪',
    items: [
      { name: '¼ Palmerita', desc: null, price: '$6.000' },
      { name: '¼ Cañoncito', desc: null, price: '$6.000' },
      { name: '¼ Maicenitas', desc: null, price: '$6.000' },
      { name: '¼ Alfajorcitos', desc: null, price: '$6.000' },
      { name: '¼ Galletas de avena', desc: null, price: '$6.000' },
      { name: '¼ Galletas de manteca', desc: null, price: '$6.000' },
      { name: '¼ Especialidad a elección', desc: null, price: '$6.000' },
    ],
  },
  {
    id: 'minutas',
    name: 'Minutas',
    emoji: '🍕',
    items: [
      { name: 'Sándwich de milanesa', desc: null, price: null },
      { name: 'Empanadas criollas', desc: null, price: null },
      { name: 'Empanadas árabes', desc: null, price: null },
      { name: 'Tarta de verdura', desc: null, price: null },
      { name: 'Tarta jamón y queso', desc: null, price: null },
      { name: 'Pizza / Pizzeta', desc: null, price: null },
    ],
  },
  {
    id: 'pastas',
    name: 'Pastas Artesanales',
    emoji: '🍝',
    items: [
      { name: 'Ravioles pollo y verdura', desc: '500gr', price: '$10.000' },
    ],
  },
];